version: '3.7'

services:
  test:
    build: .
    container_name: test
#    restart: always
    ports:
      - "8080:8080"
  db:
    container_name: pg_db
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: raw_data
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: noemail@noemail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
